server:
  port: 8081
spring:
  application.name: library-service
  sleuth:
    propagation.type: B3,W3C
    opentracing.enabled: true
  zipkin.base-url: http://localhost:9411

library.book.service: http://localhost:8082