server:
  port: 8083
spring:
  application.name: author-service
  sleuth:
    propagation.type: B3,W3C
    opentracing.enabled: true
    baggage:
      remote-fields:
        - country-code
      local-fields:
      - x-trace-id  
  zipkin.base-url: http://localhost:9411
