server:
  port: 8082
spring:
  application.name: book-service
  sleuth:
    sampler.probability: 1.0
    propagation.type: B3,W3C
    opentracing.enabled: true
    baggage:
      remote-fields:
        - country-code
      local-fields:
      - x-trace-id
  zipkin.base-url: http://localhost:9411

library.author.service: http://localhost:8083